CREATE TABLE quotes (
	id INTEGER NOT NULL, 
	author_id INTEGER NOT NULL, 
	text VARCHAR(255) NOT NULL, rating INTEGER DEFAULT '1' NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(author_id) REFERENCES authors (id)
);
